### DISCUSSION TITLE
where I can configure in drupal or dkan so that the file delimiter is a semicolon and not a comma

### DISCUSSION THREAD

**Discussion by janette** [GetDKAN/dkan#3848] [General]
Julian Hoyos

First you will need to create a custom module that will contain a subscriber that will listen for this event: EVENT_CONFIGURE_PARSER.

/src/modules/custom_module/src/EventSubscriber/Subscriber.php
```
<?php

namespace Drupal\custom_module\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Drupal\common\Events\Event;
use Drupal\datastore\Service\Import;


/**
 * Class Subscriber.
 */
class Subscriber implements EventSubscriberInterface {

  /**
   * Inherited.
   *
   * @inheritdoc
   */
  public static function getSubscribedEvents() {
    $events = [];
    $events[Import::EVENT_CONFIGURE_PARSER][] = ['set'];
    return $events;
  }

  /**
   * Customize the CSV parser config.
   *
   * @param \Drupal\common\Events\Event $event
   *   The event object containing the default config.
   */
  public function set(Event $event) {
    $parserConfiguration = $event->getData();
    $parserConfiguration['delimiter'] = ';';
    $event->setData($parserConfiguration);
  }

}
```

/src/modules/custom_module/custom_module.services.yml
```
services:
  custom_module.event_subscriber:
    class: \Drupal\custom_module\EventSubscriber\Subscriber
    tags:
      - { name: event_subscriber }
```

See: https://github.com/GetDKAN/dkan/blob/2.x/modules/datastore/src/Service/Import.php#L179
