### ISSUE TITLE
Feeds - DKAN Datastore Link Importer 

### ISSUE THREAD

**Issue by datphamict** [GetDKAN/dkan#2815]
Add a brief description about the purpose of the issue.

## Steps to Reproduce
Add steps for reproducing the issue including any file(s) needed to reproduce.

1. Add Resource
2. Feeds - DKAN Datastore Link Importer panel is show ?
3. Feeds - DKAN Datastore File  panel is show ?

![1](https://user-images.githubusercontent.com/38518509/52061851-e3018200-25a1-11e9-8141-93fb252b1cdb.PNG)
![2](https://user-images.githubusercontent.com/38518509/52061853-e5fc7280-25a1-11e9-86ce-67d208b2e647.PNG)

## Acceptance Criteria
Add the goals and desired results that this issue should accomplish when complete.

- [ ]
- [ ]
- [ ]

## Subtasks
Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [ ] Is there a test for the issue
- [ ] Is there documentation for the issue
- [ ] Are follow up tickets needed

**Comment by janette** [comment]
@datphamict what version of Feeds are you using? Only the following version of feeds is compatible with DKAN right now
```
  feeds:
    download:
      type: git
      url: https://git.drupal.org/project/feeds.git
      branch: 7.x-2.x
      revision: d312f4f66e98cc12b8462cd13874184589017f72
    patch:
      1127696: https://www.drupal.org/files/issues/1127696-137.patch
```
