### ISSUE TITLE
Workbench deadlock

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2827]
During the harvest process, when the migration was being executed we noticed that a deadlock was produced on workbench_moderation_node_history table, we found that is an issue with workbench moderation module because when a draft is created a db_update in that able is issued when the nid haven't been inserted. According to https://www.drupal.org/project/workbench_moderation/issues/2252871 these are the steps to reproduce:

- Create a draft
- db_update issue before any records for that nid inserted

We should check that after the patch is applied, then:
- When a draft is created, db_update is not issued.
- db_update is issued only on updates.

**Add patch**
```
projects:
  workbench_moderation:
    patch:
      2252871: 'https://www.drupal.org/files/issues/2252871-workbench_moderation-db_update-6.patch'
```
